ratpack:
  port: 9008

dropwizard:
  jmx: true
  slf4j:
    enabled: true
    interval: 10

server:
  port: 9000
management:
  port: 9001
  address: 127.0.0.1

db:
  file: /Users/moyong/project/env-myopensource/1-spring/12-spring/rocksdb-service/src/main/resources/data/
